enabled: true
name: cfctl
namespace: cloudforet

image:
  name: cloudforet/cfctl
  version: latest
imagePullPolicy: IfNotPresent
replicas: 1

resources: {}
#     requests:
#         memory: "128Mi"
#         cpu: "25m"
#     limits:
#         memory: "256Mi"
#         cpu: "50m"

#imagePullSecrets:
# - {imagePullSecret_name}

#serviceAccountName: {name}

#env:
# - name: key
#   value: value

pod:
  spec: {}

pvc:
  storageClassName: null # You must specify a storage class name. Otherwise, the cfctl pod will use empty volume.
  accessModes:
    - "ReadWriteMany"
  requests:
    storage: 8Gi
